input {
  tcp {
    port  => 5010
    codec => json_lines
    tags  => ["fastapi"]
  }
}

filter {
  if "fastapi" in [tags] {
    mutate {
      add_field => { "project" => "cern-db" }
    }
    date {
      match   => ["@timestamp", "ISO8601"]
      target  => "@timestamp"
    }
  }

  if [level] == "ERROR" or [level] == "CRITICAL" {
    mutate { add_tag => ["alert"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cern-db-logs-%{+YYYY.MM.dd}"
  }
}
